title: HSNA TECHNOLOGIES PRIVATE LIMITED
baseURL: /
params:
  base_font: nunito-sans
  palette: blue
  header:
    logo_img: images/hsnatech.jpg
    logo_img_alt: hsnatech.com
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: Features
        url: /features
        style: link
      - label: Pricing
        url: /pricing
        style: link
      - label: Style Guide
        url: /style-guide
        style: link
      - label: Sign Up
        url: /signup
        style: primary
  footer:
    sections:
      - type: footer_text
        image: images/perpetual-aluminum.jpg
        image_url: /
        image_alt: HSNA TECHNOLOGIES PRIVATE LIMITED
      - type: footer_nav
        title: Company
        nav_links:
          - label: About Us
            style: link
            new_window: true
            url: /about
          - label: Blog
            url: /blog
            style: link
          - label: Sign Up
            url: /signup
            style: link
          - label: Contact
            url: /contact
            style: link
      - type: footer_nav
        title: Community
        nav_links:
          - label: Twitter
            url: 'https://twitter.com/'
            style: link
            has_icon: true
            icon: twitter
            icon_position: left
          - label: FaceBook
            url: 'https://www.facebook.com/Hsnatech'
            style: link
            has_icon: true
            icon: facebook
            icon_position: left
            new_window: false
            no_follow: false
            type: action
          - url: '#'
            style: link
            has_icon: false
            icon: facebook
            icon_position: left
            new_window: false
            no_follow: false
            type: action
          - label: LinkedIn
            url: 'https://www.linkedin.com/in/shahid-hussain-abro-036a8719/'
            style: link
            has_icon: true
            icon: linkedin
            icon_position: left
          - label: GitHub
            url: 'https://github.com/shahidabro93'
            style: link
            has_icon: true
            icon: github
            icon_position: left
            new_window: true
      - type: footer_form
        title: Subscribe
        content: |

          Stay active to date with our modern advances.
        form_id: contactForm
        hide_labels: true
        form_fields:
          - input_type: email
            name: email
            label: Email
            default_value: Enter email address
            is_required: true
        submit_label: Subscribe
    has_nav: true
    nav_links:
      - label: Terms of Service
        url: '#'
        style: link
      - label: Privacy Policy
        url: '#'
        style: link
    content: "&copy; HSNA\_ TECHNOLOGIES PRIVATE LIMITED. All rights reserved."
  domain: 'https://www.hsnatech.com'
  favicon: images/perpetual-mars.jpg
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
